/*--- id:1 ---*/
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SUBSCRIPTION', 
              'CANCELED', 
              '3237bd9b244e', 
              5.98999977, 
              'USD', 
              'Welocally Places For Wordpress 1M', 
              'Our original monthly subscription', 
              0, 
              2592000000, 
              1314673289280, 
              1314673289280 ); 

/*--- id:2 ---*/              
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SUBSCRIPTION', 
              'CANCELED', 
              'cfe6bbb3d3e2', 
              5.98999977, 
              'USD', 
              'Welocally Places For Wordpress 1M', 
              'Our original monthly subscription', 
              0, 
              2592000000, 
              1314673289280, 
              1314673289280 ); 

/*--- id:3 ---*/                
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SUBSCRIPTION', 
              'AVAILABLE', 
              'f98bb3e02c3e', 
              0.00000000, 
              'USD', 
              'Welocally Places Basic', 
              'Our basic free subscription.', 
              0, 
              2592000000, 
              1314673289280, 
              1314673289280 ); 

              
/*--- id:4 ---*/                
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SUBSCRIPTION', 
              'AVAILABLE', 
              'f4e39bd78499', 
              59.98999977, 
              'USD', 
              'Welocally Places Pro', 
              'Our simple value subscription plan for one year.', 
              0, 
              31104000000, 
              1314673289280, 
              1314673289280 ); 

/*--- id:5 ---*/                
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SUBSCRIPTION', 
              'AVAILABLE', 
              '60ae07d131df', 
              249.98999977, 
              'USD', 
              'Welocally Places Premium', 
              'Unlimited use of plugins, themes and add-ons for one year.', 
              0, 
              31104000000, 
              1314673289280, 
              1314673289280 );    
              
/*--- id:6 ---*/     
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SUPPORT', 
              'AVAILABLE', 
              '242e4ca0c3ca', 
              3.98999977, 
              'USD', 
              'Paygo Support Incident', 
              'Pay per incident support for any of our products, does not include services.', 
              0, 
              31104000000, 
              1314673289280, 
              1314673289280 );       
              
/*--- id:7 ---*/     
INSERT INTO `item_sku` 
            (`version`, 
             `item_type`, 
             `status`, 
             `sku_code`, 
             `price`, 
             `currency_code`, 
             `name`, 
             `description`, 
             `is_active`, 
             `period`, 
             `time_created`, 
             `time_updated`) 
VALUES      ( 0, 
              'SERVICES', 
              'AVAILABLE', 
              '8b09e01ed6f5', 
              60.00000000, 
              'USD', 
              'Paygo Customization Services', 
              'Pay per hour customization services for Welocally products. Have our PHP, MySql and Wordpress expert developers help you make your custom site hyperlocal with Welocally Places.', 
              0, 
              3600000, 
              1314673289280, 
              1314673289280 );   
         
              