<?xml version="1.0"?>

<rule-set name="offer01"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

	<import>java.util.*</import>
    <import>com.sightlyinc.ratecred.client.offers.Offer</import>
    <import>com.sightlyinc.ratecred.model.Rater</import>
    <import>com.sightlyinc.ratecred.admin.model.RaterOfferEvaluator</import>
    
    
    <rule name="OfferInRaterMostReviewedCityState">
    	<parameter identifier="evaluator">
               <class>RaterOfferEvaluator</class>
        </parameter>
        <parameter identifier="offer">
               <class>Offer</class>
		</parameter>
    	
		 <java:condition>
             evaluator.isInMostRatedCity(offer)
         </java:condition>

        <java:consequence>
           System.out.println("Offer is in most rated city");
           evaluator.addOffer(offer,1);
           drools.modifyObject(evaluator);
        </java:consequence>
        
    </rule>
    
 
	

  </rule-set>
