<?xml version="1.0"?>

<rule-set name="target_offers"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <import>com.sightlyinc.ratecred.client.offers.Offer</import>
    <import>com.sightlyinc.ratecred.admin.model.AwardOfferEvaluator</import>
    
    
    <rule name="addOffer" salience="80">
   		<parameter identifier="offer">
            <class>com.sightlyinc.ratecred.client.offers.Offer</class>
        </parameter>
		<parameter identifier="offer_target">
            <class>com.sightlyinc.ratecred.admin.model.OfferTargetEvaluator</class>
        </parameter> 
        <java:condition>offer.isVisible()</java:condition>  
        <java:condition>offer_target.isExternalSource("ADILITY", offer)</java:condition>
        
        
        <java:consequence>
        	offer_target.addOfferToCache(offer); 
        </java:consequence>
    </rule>       
 
    
    <rule name="localOffer" salience="40">
        <parameter identifier="offer">
            <class>com.sightlyinc.ratecred.client.offers.Offer</class>
        </parameter>
		<parameter identifier="offer_target">
            <class>com.sightlyinc.ratecred.admin.model.OfferTargetEvaluator</class>
        </parameter> 
        <java:condition>offer.isVisible()</java:condition>  
        <java:condition>offer_target.isExternalSource("ADILITY", offer)</java:condition>     
        <java:condition>offer_target.isLocalOffer(offer)</java:condition>
              
        <java:consequence>
        	offer.addScore(5); 
        </java:consequence>
    </rule>
    
        
   
       
     
    
	
  </rule-set>
